// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6QnUxvWEMmRjlDQR682_89MYDcc52nXg',
    appId: '1:318171990865:web:834c60c1176a98b2a62170',
    messagingSenderId: '318171990865',
    projectId: 'fire-base-1b418',
    authDomain: 'fire-base-1b418.firebaseapp.com',
    storageBucket: 'fire-base-1b418.appspot.com',
    measurementId: 'G-E6KYHZP22J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq7mkvZyMlz_RvVXnRaXGw5q60B0myDd0',
    appId: '1:318171990865:android:330d45f0dd247261a62170',
    messagingSenderId: '318171990865',
    projectId: 'fire-base-1b418',
    storageBucket: 'fire-base-1b418.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2O0a_-5M1jLwbna9UtE2NqmjLy_HwkVk',
    appId: '1:318171990865:ios:165042a6095086d0a62170',
    messagingSenderId: '318171990865',
    projectId: 'fire-base-1b418',
    storageBucket: 'fire-base-1b418.appspot.com',
    iosClientId: '318171990865-np4ubd66q974cudncismrsuhv72agduk.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2O0a_-5M1jLwbna9UtE2NqmjLy_HwkVk',
    appId: '1:318171990865:ios:165042a6095086d0a62170',
    messagingSenderId: '318171990865',
    projectId: 'fire-base-1b418',
    storageBucket: 'fire-base-1b418.appspot.com',
    iosClientId: '318171990865-np4ubd66q974cudncismrsuhv72agduk.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
